config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations }
  root to: 'rooms#index'

  resources :users, only: [:show]
  get 'users/:id/direct', to: 'users#direct_message', as: 'direct_message'
  
  resources :rooms do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_create_commit { broadcast_append_to room }

  before_create :confirm_participant

  has_many_attached :attachments, dependent: :destroy

  def chat_attachment(index)
    target = attachments[index]
    return unless attachments.attached?
    return target if %w[image/gif].include?(target.content_type)

    target.variant(resize_to_limit: [150, 150]).processed
  end

  def confirm_participant
    return unless room.is_private

    is_participant = Participant.where(user_id: user.id, room_id: room.id).first
    throw :abort unless is_participant
  end

  def today?
    created_at.to_date.eql? Date.current
  end

  def this_week?
    created_at >= Date.current.at_beginning_of_week
  end

  def this_year?
    created_at.year.eql? Date.current.year
  end

  def display_time
    return created_at.strftime('%H:%M') if today?
    return created_at.strftime('%A %H:%M') if this_week?
    return created_at.strftime('%d %b %H:%M') if this_year?

    created_at.strftime('%d %b %Y %H:%M')
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true

  scope :public_rooms, -> { where(is_private: false) }

  after_create_commit { broadcast_if_public }

  # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :messages
  # rubocop:enable Rails/HasManyOrHasOneDependent

  has_many :participants, dependent: :destroy

  def broadcast_if_public
    broadcast_append_to 'rooms' unless is_private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id)
    end

    single_room
  end

  def participant?(room, user)
    room.participants.exists?(user: user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  validates :avatar, content_type: ['image/png', 'image/jpg', 'image/jpeg'],
                     allow_nil: true

  scope :all_except, ->(user) { where.not(id: user) }

  after_create_commit { broadcast_append_to 'users' }
  after_update_commit { broadcast_update }

  enum status: { offline: 0, away: 1, online: 2 }

  # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :messages
  # rubocop:enable Rails/HasManyOrHasOneDependent

  def broadcast_update
    broadcast_replace_to 'user_status', partial: 'users/status', user: self
  end

  def status_to_css
    case status
    when 'online'
      'bg-success'
    when 'away'
      'bg-warning'
    else
      'bg-dark'
    end
  end

  def display_avatar
    return avatar if avatar.attached?

    'avatar.svg'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_status

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:email, :password, :password_confirmation)
    end

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit :first_name, :last_name, :birthdate, :email,
               :password, :password_confirmation, :current_password, :avatar
    end
  end

  private

  def set_status
    current_user&.update!(status: User.statuses[:online])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = current_user.messages.create(
      body: message_params[:body],
      room_id: params[:room_id],
      attachments: message_params[:attachments]
    )
  end

  private

  def message_params
    params.require(:message).permit(:body, attachments: [])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :single_room, only: [:show]
  before_action :rooms, only: [:index, :show]
  before_action :users, only: [:index, :show]

  def index
    @room = Room.new

    render 'index'
  end

  def show
    @message  = Message.new
    @messages = single_room.messages.order(created_at: :asc)
    @room     = Room.new

    render 'index'
  end

  def create
    @room = Room.create(room_params)
  end

  private

  def single_room
    @single_room ||= Room.find(params[:id])
  end

  def users
    @users ||= User.all_except(current_user)
  end

  def rooms
    @rooms ||= Room.public_rooms
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user
  before_action :users, only: [:direct_message]
  before_action :rooms, only: [:direct_message]

  def show; end

  def direct_message
    @room        = Room.new
    @room_name   = get_name(user, current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room(
      [user, current_user], @room_name
    )

    @message  = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    render 'rooms/index'
  end

  private

  def get_name(user1, user2)
    users = [user1, user2].sort
    "private_#{users[0].id}_#{users[1].id}"
  end

  def user
    @user ||= User.find(params[:id])
  end

  def users
    @users ||= User.all_except(current_user)
  end

  def rooms
    @rooms ||= Room.public_rooms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatty</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <style>
    <% if current_user %>
      <%= ".message-#{current_user.id}" %> {
        margin: 2px 10px;
        text-align: right;
      }

      <%= ".message-#{current_user.id}" %> > .d-flex {
        justify-content: flex-end;
      }

      <%= ".message-#{current_user.id}" %> > .d-flex > .avatar {
        margin-left: 5px;
        order: 1;
      }

      <%= ".message-#{current_user&.id}" %> > .d-flex > .body {
        background-color: #2e59d9;
        color: white;
        margin-left: 0;
      }

      <%= ".message-#{current_user&.id}" %> > .d-flex > .body > .time {
        text-align: left;
      }

      <%= ".message-#{current_user&.id}" %> > .d-flex > .body > .name {
        color: white;
        opacity: 80%;
      }

      <%= ".message-wrapper-#{current_user&.id}" %> {
        display: flex;
        justify-content: flex-end
      }
    <% end %>
  </style>

  <body class="<%= current_user ? 'bg-secondary' : '' %>">
    <% content_for :alert do %>
      <%= render 'shared/flashes' %>
    <% end %>

    <% if current_user %>
      <%= render 'shared/navbar' %>

      <div class="container-fluid h-auto">
        <div class="row">
          <main role="main" class="col-12 px-4">
            <div class="row">
              <div class="col-sm-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
                <%= yield :alert %>
              </div>
            </div>

            <div class="row">
              <div class="col-sm-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
                <%= yield %>
              </div>
            </div>
          </main>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>

  <script src="https://use.fontawesome.com/74c965c3f8.js"></script>
</html>

app/views/messages/_message.html.erb
<% user = message.user %>

<div class="message-wrapper-<%=message.user.id%>">
  <div class="message-box message-<%= message.user.id %>">
    <div class="d-flex">
      <div class="avatar avatar__small">
        <%= image_tag user.display_avatar %>
      </div>

      <div class="body">
        <h6 class="name"> <%= user.email %></h6>
        <p class="content"><%= message.body %></p>
        <% if message.attachments.attached? %>
          <% message.attachments.each_with_index do |attachment, index| %>
            <% if attachment.image? %>
              <%= image_tag(message.chat_attachment(index)) %>
            <% elsif attachment.video? %>
              <%= video_tag(url_for(attachment), style:'height:auto; width:100%', controls:'') %>
            <% elsif attachment.audio? %>
              <%= audio_tag(url_for(attachment), controls: '') %>
            <% else %>
              <%= link_to attachment.filename, url_for(attachment), style:"text-decoration: none; color: #fff" %>
            <% end %>
          <% end %>
        <% end %>
        <p class="time"><%= message.display_time %></p>
      </div>
    </div>
  </div>
</div>

app/views/messages/_new_message_form.html.erb
<%= form_with(model: [@single_room, @message], remote: true, class: 'd-flex message-form',
              data: { controller: 'reset-form', action: 'turbo:submit-end->reset-form#reset' } ) do |f| %>
  <div id="attachment-previews"
       data-controller="message-preview"
       data-action="message-preview#preview">
  </div>

  <div class="image-upload">
    <label for="message_attachments">
      <i class="fa fa-plus-circle upload-button"></i>
    </label>

    <%= f.file_field(:attachments, multiple: true, data: { controller: "message-preview", action:"change->message-preview#preview" }) %>
  </div>

  <%= f.text_field :body, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off' %>
  <%= f.submit "Send",
      data: { disable_with: false, controller: "message-preview", action:"click->message-preview#clearPreviews" }, 
      class: 'btn btn-primary' %>
<% end %>

app/views/rooms/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: 'd-flex room-form',
              data: { controller: 'reset-form', action: 'turbo:submit-end->reset-form#reset' }) do |f| %>
  <%= f.text_field :name, class: 'form-control', autocomplete: 'off' %>
  <%= f.submit data: { disable_with: false }, class: 'btn btn-secondary' %>
<% end %>

app/views/rooms/_room.html.erb
<li class="list-group-item d-flex align-items-center justify-content-between <%= @single_room.eql?(room) ? 'active' : '' %>">
  <div class="room">
    <%= link_to room.name, room %>
  </div>
</li>

app/views/rooms/index.html.erb
<%= turbo_frame_tag "appearance_channel" %>
<div id="appearance_channel"></div>

<div class="chatroom_container row bg-white mt-3">
  <%= render 'shared/side_panel', users: @users, rooms: @rooms %>

  <div class="room_container col-sm-8 col-md-8 col-lg-8 p-0">
    <% if @single_room %>
      <div id="single_room">
        <div class="header bg-light">
          <div class="d-flex">
            <div class="info">
              <h4 class="m-0"><%= @user&.email || @single_room.name %></h4>
            </div>
          </div>
        </div>

        <%= turbo_stream_from @single_room %>
        <div id="messages" data-controller="scroll">
          <%= render @messages %>
        </div>
          <%= render 'messages/new_message_form' %>
      </div>
    <% else %>
      <div class="room-icon text-center">
        <i class="fa fa-weixin"></i>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<div class='alert-container mt-5' id='flashes'>
  <% if notice.present? %>
    <div class="alert alert-success col-sm-12 col-md-12" role="alert">
      <%= notice.html_safe %>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-warning col-sm-12 col-md-12" role="alert">
      <%= flash[:alert].html_safe %>
    </div>
  <% end %>
  <% if flash[:error] %>
    <div class="alert alert-danger col-sm-12 col-md-12" role="alert">
      <% if flash[:error].is_a?(Array) %>
        <% flash[:error].each do |error| %>
          <%= error.html_safe %>
          <br />
        <% end %>
      <% else %>
        <%= flash[:error].html_safe %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <%= image_tag image_url('logo.png'), class: "logo" %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
            <%= current_user.email %>
          </a>

          <div class="dropdown-menu">
            <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>

            <div class="dropdown-divider"></div>

            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link', id: 'sign-out', data: { turbo: false } %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link', id: 'sign-in' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_side_panel.html.erb
<div class="side_panel col-sm-4 col-md-4 col-lg-4 text-light">
  <div class="side_panel__logo">
    <%= link_to image_tag('logo2.png'), root_path %>
  </div>
  <div class="side_panel__current_user">
    <div class="avatar avatar__small">
      <%= image_tag current_user.display_avatar %>
      <%= turbo_stream_from "user_status" %>

      <div class="icon-status">
        <%= render "users/status", user: current_user %>
      </div>
    </div>
    <h5><%= link_to current_user.email, current_user %></h5>
  </div>

  <div class="side_panel__info">
    <h4>Users</h4>
    <%= turbo_stream_from "users" %>
    <div id="users">
      <%= render users %>
    </div>

    <h4>Rooms</h4>
    <%= render 'rooms/new_room_form' %>
    <%= turbo_stream_from "rooms" %>
    <div id="rooms">
      <%= render rooms %>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block sidebar p-0">
  <div class="sidebar-sticky margin-top-50">
    <ul class="nav flex-column">
      <li class="nav-item <%= request.path == '/' ? 'active' : '' %>">
        <%= link_to root_path, class: "nav-link", target: "_top" do %>
          <i class="fa fa-home"></i> Home
        <% end %>
      </li>

      <li class="nav-item <%= request.path.include?('rooms') ? 'active' : '' %>">
        <%= link_to rooms_path, class: "nav-link", target: "_top" do %>
          <i class="fa fa-weixin"></i> Rooms
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/users/_status.html.erb
<%= turbo_frame_tag "user_status" %>
<div class="status-circle <%= user.status_to_css %>" id="<%= dom_id(user) %>"></div>

app/views/users/_user.html.erb
<% if @single_room && @single_room.participant?(@single_room, user) %>
  <% isActive = 'active' %>
<% else %>
  <% isActive = '' %>
<% end %>

<li class="list-group-item d-flex align-items-center justify-content-between <%= isActive %>">
  <div class="user">
    <div class="avatar avatar__small">
      <%= link_to image_tag(user.display_avatar), direct_message_path(user) %>
      <%= turbo_stream_from "user_status" %>

      <div class="icon-status">
        <%= render "users/status", user: user %>
      </div>
    </div>

    <%= link_to user.email, direct_message_path(user) %>
  </div>
</li>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/shared/_photo_credit.html.erb
<div class="col">
  <div class="background">
    <p class="credit">Photo by <a href="https://unsplash.com/@brookecagle" class="text-white">Brooke Cagle on Unsplash</a></p>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-12">
    <div class="card card__custom mb-4">
      <div class="card-header">
        <div class="row">
          <div class="col-xs-10 col-sm-10 col-md-8 col-lg-6">
            <h2><%= @user.eql?(current_user) ? 'My Profile' : 'Profile' %></h2>
          </div>
          <div class="col-xs-2 col-sm-2 col-md-4 col-lg-6 text-right">
            <% if @user.eql? current_user %>
              <%= link_to edit_user_registration_path, class: 'btn btn-info', id: 'edit-user' do %>
                <i class="fa fa-pencil"></i> Edit
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="card-body">
        <div class="row">
          <div class="col-12">
            <div class="avatar">
              <%= image_tag @user.display_avatar %>
            </div>

            <div class="form-group">
              <label>First Name</label>
              <p><%= @user.first_name %></p>
            </div>

            <div class="form-group">
              <label>Last Name</label>
              <p><%= @user.last_name %></p>
            </div>

            <div class="form-group">
              <label>Birthdate</label>
              <p><%= @user.birthdate&.strftime('%d %B %Y') %></p>
            </div>

            <div class="form-group">
              <label>Email</label>
              <p><%= @user.email %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>